
#      ___             __               ____     _____
#     / _ )___ ___ _  / /  ___  ___    / __/__  / _/ /__    _____ ________
#    / _  / _ `/  ' \/ _ \/ _ \/ _ \  _\ \/ _ \/ _/ __/ |/|/ / _ `/ __/ -_)
#   /____/\_,_/_/_/_/_.__/\___/\___/ /___/\___/_/ \__/|__,__/\_,_/_/  \__/
#
#   Docker Compose for Run Bamboo Server
#   Test for bitbucket Server 9.x
#   Need  "my-net" Network for Run this File
#   docker network create --driver bridge --subnet=172.16.50.0/24 my-net

version: "3.4"
services:
  bamboo:
    image: atlassian/bamboo-server:latest
    restart: always
    container_name: bamboo
    hostname: bamboo
    environment:
      JAVA_OPTS: '-javaagent:/atlassian-agent.jar'
      JVM_MINIMUM_MEMORY: 1024m
      JVM_MAXIMUM_MEMORY: 2048m
      JVM_RESERVED_CODE_CACHE_SIZE: 512m
      #   If Use Reverse Proxy Uncomment this Line
      ATL_TOMCAT_SCHEME: 'https'
      ATL_TOMCAT_SECURE: 'true'
      ATL_PROXY_PORT: '443'
      ATL_PROXY_NAME: 'bamboo.domen.com'
    volumes:
      - ./bamboo-vol:/var/atlassian/application-data/bamboo
      - ./agent/atlassian-agent.bak:/atlassian-agent.jar:ro
    networks:
      my-net:
       aliases:
        - bamboo
    ports:
      - 54663:54663
      - 8085:8085

networks:
  my-net:
    external: true
volumes:
  bamboo-vol:
    name: bamboo-vol
