#
#   __   _ __  __            __       __    ____     _____
#  / /  (_) /_/ /  __ ______/ /_____ / /_  / __/__  / _/ /__    _____ ________
# / _ \/ / __/ _ \/ // / __/  '_/ -_) __/ _\ \/ _ \/ _/ __/ |/|/ / _ `/ __/ -_)
#/_.__/_/\__/_.__/\_,_/\__/_/\_\\__/\__/ /___/\___/_/ \__/|__,__/\_,_/_/  \__/
#
#   Docker Compose for Run bitbucket
#   Test for bitbucket Server 7.x
#   Need  "my-net" Network for Run this File
#   docker network create --driver bridge --subnet=172.16.50.0/24 my-net

version: '3.4'
services:
  bitbucket:
    image: atlassian/bitbucket-server:7.10.0
    container_name: bitbucket
    hostname: bitbucket
    restart: always
    environment:
      #JDBC_OPTS: '-javaagent:/atlassian-agent.jar'
      #JDBC_DRIVER: org.postgresql.Driver
      #JDBC_USER: bitbucket
      #JDBC_PASSWORD: 'ueeHWugC!@80'
      SERVER_SCHEME: 'https'
      SERVER_SECURE: 'true'
      SERVER_PROXY_PORT: '443'
      SERVER_PROXY_NAME: 'bitbucket.becloud.by'
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 2048m
      JVM_RESERVED_CODE_CACHE_SIZE: 512m
    volumes:
      - .bitbucket-Data:/var/atlassian/application-data/bitbucket
      #- ./agent/atlassian-agent-jar-with-dependencies.jar:/atlassian-agent.jar:ro
    networks:
      my-net:
       aliases:
        - bit
    ports:
      - 7990:7990
      - 7999:7999

networks:
  my-net:
    external: true
