#      ____     __                  ____      _____             _ __   __
#     / _(_)__ / /  ___ __ _____   / __/___  / ___/_____ ______(_) /  / /__
#    / _/ (_-</ _ \/ -_) // / -_)  > _/_ _/ / /__/ __/ // / __/ / _ \/ / -_)
#   /_//_/___/_//_/\__/\_, /\__/  |_____/   \___/_/  \_,_/\__/_/_.__/_/\__/
#                     /___/
#   Docker Compose for Run Fisheye & Crucible
#   Test for Fisheye Server 9.x
#   Need  "my-net" Network for Run this File
#   docker network create --driver bridge --subnet=172.16.50.0/24 my-net

version: "3.4"
services:
  fisheye:
    image: atlassian/fisheye:latest
    restart: always
    container_name: fisheye
    hostname: fisheye
    environment:
      FISHEYE_OPTS: '-javaagent:/atlassian-agent.jar'
      JVM_MINIMUM_MEMORY: 1024m
      JVM_MAXIMUM_MEMORY: 2048m
      JVM_RESERVED_CODE_CACHE_SIZE: 1024m
    volumes:
      - ./agent/atlassian-agent.bak:/atlassian-agent.jar:ro
    networks:
      my-net:
       aliases:
        - fisheye
    ports:
      - 8059:8059
      - 8080:8080

networks:
  my-net:
    external: true
volumes:
  fisheye-vol:
    name: fisheye-vol
